# Generated by Django 6.0.7 on 2026-07-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backupcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackupCode',
            new_name='UserBackupCode',
        ),
        migrations.AlterModelTable(
            name='userbackupcode',
            table='user_backup_codes',
        ),
    ]
