"""
Django settings for system-base project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$6b7f22ypw6o%h%jen%^+5)s*gfoqm+4y5qjc*ajsh=&^q3^_x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps
    'apps.accounts',
    'apps.departments',
    'apps.authorization',
    'apps.core',
    # Third Party apps
    'django_recaptcha'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'

# Aponta para o nosso modelo de User customizado
AUTH_USER_MODEL = "accounts.User"
# Define a estratégia de autenticação
AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.EmailAuthenticationBackend",
    "apps.authorization.backends.CustomAuthorizationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "core:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True
PASSWORD_RESET_TIMEOUT = 60 * 60 * 1  # # Tempo de validade do link de recuperação de senha (em segundos) - Expira em 1 hora (3600 segundos)

# Em ambiente de produção (com HTTPS ativado), force o uso de cookies seguros:
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# Impressão de e-mails no terminal em ambiente de desenvolvimento
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@seusistema.com.br"

#DJANGO-RECAPTCHA CONFIG
RECAPTCHA_PUBLIC_KEY = "6Ldep14tAAAAAEOgRol3SqEY3Famrnezf_Wov6aN"
RECAPTCHA_PRIVATE_KEY = "6Ldep14tAAAAAEO5lzQ9vT5zhYZbPunV1XC33lMH"

#DJANGO-RATELIMIT CONFIG
RATELIMIT_USE_CACHE = "default"
NUM_PROXIES = 0 # Em desenvolvimento você acessa direto (Ex: localhost:8000), então zero proxies; Se usar apenas Nginx ou apenas Cloudflare na frente do Django = 1; Se usar Cloudflare + Nginx juntos na frente do Django = 2