# Generated by Django 6.0.7 on 2026-07-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='DepartmentPermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_templates', to='departments.department', verbose_name='Departamento')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_templates', to='authorization.permission', verbose_name='Permissão')),
            ],
            options={
                'verbose_name': 'Template de Permissão do Departamento',
                'verbose_name_plural': 'Templates de Permissões dos Departamentos',
                'db_table': 'department_permission_templates',
                'constraints': [models.UniqueConstraint(fields=('department', 'permission'), name='unique_department_permission_template')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('department', 'Departamento')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_links_granted', to=settings.AUTH_USER_MODEL)),
                ('origin_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to='departments.department')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='authorization.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão do Usuário',
                'verbose_name_plural': 'Permissões dos Usuários',
                'db_table': 'user_permissions',
                'constraints': [models.UniqueConstraint(fields=('user', 'permission'), name='unique_user_permission')],
            },
        ),
    ]
